:base: &base
  :sinatra_settings:
    :show_exceptions: <%= not ENV['RACK_ENV'] == 'production' %>
  :rack:
    :mount_url: '/cas'
  :templates:
    :path: lib/views
    :error_500_html: lib/views/500.html
    :error_404_html: lib/views/404.html
  :server:
    :gem: webrick
    :port: 443
    :ssl_cert: ./lib/misc/demo.crt
    :ssl_key: ./lib/misc/demo.key
  :cas:
    :permanent_id_column: permanent_id
    :extra_attributes: [email, first_name, last_name, locale]
  :authenticators:
    - :class: CasFuji::Authenticators::TestAuth
      :source: ./lib/authenticators/test_auth.rb
  :authorizer:
    :class: CasFuji::Authorizer
    :source: ./lib/authorizer.rb
  :organization:
    :name: Your Org Name
    :tagline: The name on the default login template
  :default_locale: en
  :log:
    :file: ./log/cas_fuji.log
    :level: DEBUG
    db_log: ./log/cas_fuji_db.log
  :quiet: false
  :ticket_granting_ticket:
    :session_length: <%= 15 * 24 * 60 * 60 %> # 15 days in seconds

test:
  <<: *base
  :rack:
    :mount_url: '/'
  :database:
    adapter: postgresql
    database: cas_fuji_test
    username: 
    password: 
    pool: 5
    timeout: 5000
  :quiet: true

development:
  <<: *base
  :database:
    adapter: postgresql
    database: cas_fuji_development
    username: 
    password: 
    pool: 5
    timeout: 5000

production:
  <<: *base
  :database:
    adapter: postgresql
    database: cas_fuji_production
    username: 
    password: 
    pool: 5
    timeout: 5000

